### PR TITLE
Update Dependencies 

### PR DESCRIPTION
**Pull request by mmorel-35**
This PR updates github-actions, go, npm and docker dependencies.
I have used dependabot and let the config in the pr in case you'd want it

### CODE REVIEW

**Comment by TomWright** [comment]
Hey @mmorel-35,

Thanks for the PR.

Have you tested this at all? There are a couple of version changes that jump some major versions

**Comment by mmorel-35** [comment]
Hi @TomWright, the github testing workflow was passing for all the updates.

**Comment by TomWright** [comment]
@mmorel-35 yeah I saw. This package contains a few moving parts and is lacking integration tests. I'll pull this branch and do some local testing.
I had another dependabot PR which was merged which is why there are now clashes

**Comment by TomWright** [comment]
Thanks for your contribution

**Pull request merged**
